# Training_option
Training:
  BATCH_SIZE: 4
  OUTPUT_PATH: '/home/cvip/BigDisk/imagepro/Result/SegmentMatting/output_image'
  OPTIMIZER: 'Adam'
  LR: 0.01
  EPOCH: 300
  LogPath: '/home/cvip/BigDisk/imagepro/Result/SegmentMatting/log'
  PtPath: '/home/cvip/BigDisk/imagepro/Result/SegmentMatting/pt_result'
  Pretrained: True

# LOADER_OPTION
Loader:
  INPUT_W: 512
  INPUT_H: 512
  #rgb, gray, etc...(add on)
  INPUT_TYPE: 'RGB'
  SUB_INPUT: 0
  CropShape: [512, 512]

  INPUT_PATH: '/home/cvip/BigDisk/imagepro/Dataset/HumanDataset/train/input'
  GT_PATH: '/home/cvip/BigDisk/imagepro/Dataset/HumanDataset/train/gt'
  HINT_PATH: '/'
  Valid_Path: '/home/cvip/BigDisk/imagepro/Dataset/HumanDataset/test/input'
  GT_valid: '/home/cvip/BigDisk/imagepro/Dataset/HumanDataset/test/gt'

# NETWORK_OPTION
Network:
  INPUT_CHANNEL: 3
  OUTPUT_CHANNEL: 1
  BASIC_CHANNEL: 32