# Training_option
Training:
  BATCH_SIZE: 4
  OUTPUT_PATH: ''
  OPTIMIZER: 'Adam'
  LR: 0.0001
  EPOCH: 80
  LogPath: ''
  PtPath: ''
  Pretrained: True

# LOADER_OPTION
Loader:
  INPUT_W: 512
  INPUT_H: 512
  #rgb, gray, etc...(add on)
  INPUT_TYPE: 'RGB'
  SUB_INPUT: 0
  CropShape: [512, 512]

  INPUT_PATH: '/path of '
  GT_PATH: '/path of training set ground truth'
  HINT_PATH: '/not-used'
  Valid_Path: '/path of validation sets'
  GT_valid: '/path of validation sets ground truth'

# NETWORK_OPTION
Network:
  INPUT_CHANNEL: 3
  OUTPUT_CHANNEL: 1
  BASIC_CHANNEL: 32