# Training_option
Training:
  BATCH_SIZE: 2
  OUTPUT_PATH: 'D:/Dataset/MattingTest/own_test/output'
  OPTIMIZER: 'Adam'
  LR: 0.01
  EPOCH: 40
  LogPath: 'D:/Dataset/MattingTest/own_test/log'
  PtPath: 'D:/Dataset/MattingTest/own_test/pt'
  Pretrained: True

# LOADER_OPTION
Loader:
  INPUT_W: 512
  INPUT_H: 512
  #rgb, gray, etc...(add on)
  INPUT_TYPE: 'RGB'
  SUB_INPUT: 0
  CropShape: [512, 512]

  INPUT_PATH: 'D:/Dataset/dataset/training'
  GT_PATH: 'D:/Dataset/MattingTest/own_test/gt'
  HINT_PATH: '/'
  Valid_Path: 'D:/Dataset/dataset/testing'
  GT_valid: 'D:/Dataset/dataset/testing_gt'

# NETWORK_OPTION
Network:
  INPUT_CHANNEL: 3
  OUTPUT_CHANNEL: 1
  BASIC_CHANNEL: 32