# Training_option
Training:
  BATCH_SIZE: 4
  OUTPUT_PATH: 'Output_path'
  OPTIMIZER: 'Adam'
  LR: 0.0001
  EPOCH: 80
  LogPath: 'Log Path'
  PtPath: 'Pt save Path'
  Pretrained: False

# LOADER_OPTION
Loader:
  INPUT_W: 512
  INPUT_H: 512
  #rgb, gray, etc...(add on)
  INPUT_TYPE: 'RGB'
  SUB_INPUT: 0
  CropShape: [512, 512]

  INPUT_PATH: '/input image path'
  GT_PATH: '/ground truth image path'
  HINT_PATH: '/'
  Valid_Path: '/ validation image path'
  GT_valid: '/ground truth image path(validation)'

# NETWORK_OPTION
Network:
  INPUT_CHANNEL: 3
  OUTPUT_CHANNEL: 1
  BASIC_CHANNEL: 32